@url = https://dhm3122da5.execute-api.ap-southeast-2.amazonaws.com

###
POST {{url}}/user
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@email.com",
  "password_hash": "TestPassword123!"
}

###
GET {{url}}/auth
Content-Type: application/json

{
  "username": "testuser",
  "password_hash": "TestPassword123!"
}
